version: '3'

services:
  mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_DATABASE: database_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
    command: --character-set-server=utf8
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./db-setup/db-dev.sql:/docker-entrypoint-initdb.d/sql-setup.sql
  app:
    build: .
    ports:
      - 8000:3000
    environment:
      PORT: 3000
    depends_on:
      - mysql
volumes:
  db: